version: '3.6'

services:
  redis:
    image: redis:5-alpine
    container_name: redis
    ports:
      - 6379:6379
    restart: always

  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: rabbitmq
    ports:
      - "7001:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  